FORMAT: 1A
HOST: http://leor.localhost/

# LEOR

## Source Collection [/sources]

### List All Sources [GET]

After sending a source as a filter, list all those sources 

+ Request (application/json)

            {
                
                "title": "ENEM/2015",
                "published_at": "2017-07-11",
                "year": "2015",
                "institute": "UFPB",
                "link": "http://www.ufpb.br/arquivos/enem2015"
            
            }

+ Response 200 (application/json)

    + Body
        
            [
            
                {
            
                    "title": "ENEM/2014",
                    "published_at": "2017-07-11",
                    "year": "2014",
                    "institute": "UFPB",
                    "link": "http://www.ufpb.br/arquivos/enem2014"
            
                },
                {
            
                    "title": "ENEM/2015",
                    "published_at": "2017-07-11",
                    "year": "2015",
                    "institute": "UFPB",
                    "link": "http://www.ufpb.br/arquivos/enem2015"

                }
                
            ]   

+ Request (application/json)

            {
        
                "title": "ENEM/2015",
                "published_at": "2017-07-11",
                "year": "2015",
                "institute": "UFPB",
                "link": "http://www.ufpb.br/arquivos/enem2015"
            
            }

+ Response 204


### Create a New Source  [POST]

Create a new source through an object

+ Request (application/json)

        {
            "title": "NEW - ENEM/2015",
            "published_at": "NEW - 2017-07-11",
            "year": "NEW - 2015",
            "institute": "UFPB",
            "link": "NEW - http://www.ufpb.br/arquivos/enem2017"
        }

+ Response 201 (application/json)

        Result OK for new 

## Source [/sources/{source_id}]

Answer from a source through a *source_id*.

### Get a source [GET]
+ Request 

    + Headers

            Location: /sources/{source_id}

+ Response 200 (application/json)

    + Body

            {
        
                "title": "ENEM/2014",
                "published_at": "2017-07-11",
                "year": "2014",
                "institute": "UFPB",
                "link": "http://www.ufpb.br/arquivos/enem2014"
        
            }

+ Response 204 

### Delete [DELETE]

+ Request 

    + Headers

            Location: /sources/{source_id}

+ Response 204

### Update [PUT]

+ Request 

    + Headers

            Location: /sources/{source_id}
    + Body

            {
        
                "title": "other title",
                "published_at": "other 2017-07-11",
                "year": "other 2014",
                "institute": "UFPB",
                "link": "other http://www.ufpb.br/arquivos/enem2014"
        
            }
                
+ Response 201 (application/json)

        Result OK for new 


## AlternativeType Collection [/alternativetypes]

### List All alternativetypes [GET]

List all alternativetypes 

+ Request (application/json)

            {
                
                "description": "A..E",
                "options": "ABCDE"
            
            }

+ Response 200 (application/json)

    + Body
        
            [
            
                {
            
                "description": "A..E",
                "options": "ABCDE"
            
                },
                {
            
                "description": "A..E",
                "options": "ABCDE"

                }
                
            ]   

+ Request (application/json)

            {
        
                "description": "A..E",
                "options": "ABCDE"
            
            }

+ Response 204


### Create a New Source  [POST]

Create a new AlternativeType through an object

+ Request (application/json)

        {

                "description": "A..E",
                "options": "ABCDE"

        }

+ Response 201 (application/json)

        Result OK for new 

## Source [/alternativetypes/{alternativetypes_id}]

### Get a source [GET]
+ Request 

    + Headers

            Location: /alternativetypes/{alternativetypes_id}

+ Response 200 (application/json)

    + Body

            {
        
                "description": "A..E",
                "options": "ABCDE"
        
            }

+ Response 204 

### Delete [DELETE]

+ Request 

    + Headers

            Location: /alternativetypes/{alternativetypes_id}

+ Response 204

### Update [PUT]

+ Request 

    + Headers

            Location: /alternativetypes/{alternativetypes_id}
    + Body

            {
        
                "description": "A..E",
                "options": "ABCDE"
        
            }
                
+ Response 201 (application/json)

        Result OK for new 

## Subjects Collection [/subjects]

### List All Subjects [GET]

List all subjects 

+ Request (application/json)

            {
                
                "description": "A..E",
                "options": "ABCDE"
            
            }

+ Response 200 (application/json)

    + Body
        
            [
            
                {
            
                "description": "A..E",
                "options": "ABCDE"
            
                },
                {
            
                "description": "A..E",
                "options": "ABCDE"

                }
                
            ]   

+ Request (application/json)

            {
        
                "description": "A..E",
                "options": "ABCDE"
            
            }

+ Response 204


### Create a New Subject  [POST]

+ Request (application/json)

        {

                "description": "A..E",
                "options": "ABCDE"

        }

+ Response 201 (application/json)

        Result OK for new 

## Subjects [/subjects/{subject_id}]

Answer from a subject through a *subject_id*.

### Get a subject [GET]
+ Request 

    + Headers

            Location: /subjects/{subject_id}

+ Response 200 (application/json)

    + Body

            {
        
                "description": "A..E",
                "options": "ABCDE"
        
            }

+ Response 204 

### Delete [DELETE]

+ Request 

    + Headers

            Location: /subjects/{subject_id}

+ Response 204

### Update [PUT]

+ Request 

    + Headers

            Location: /subjects/{subject_id}
    + Body

            {
        
                "description": "A..E",
                "options": "ABCDE"
        
            }
                
+ Response 201 (application/json)

        Result OK for new 

## Contents Collection [/contents]

### List All contents [GET]

List all contents 

+ Request (application/json)

            {
                        "subject" :
                        {
                
                                    "description": "A..E",
                                    "options": "ABCDE"
                        },
                        "description": "Adjetivos"
            
            }

+ Response 200 (application/json)

    + Body
        
            [
                        {
                                    "subject" :
                                    {
                            
                                                "description": "A..E",
                                                "options": "ABCDE"
                                    },
                                    "description": "Adjetivos"
            
                        },
                        {
                                    "subject" :
                                    {
                            
                                                "description": "A..E",
                                                "options": "ABCDE"
                                    },
                                    "description": "Adjetivos"
            
                        }

            ]   

+ Request (application/json)

            {
                        "subject" :
                        {
                
                                    "description": "A..E",
                                    "options": "ABCDE"
                        },
                        "description": "Adjetivos"
            
            }

+ Response 204


### Create a new content  [POST]

Create a new content through an object

+ Request (application/json)

            {
                        "subject" :
                        {
                
                                    "description": "A..E",
                                    "options": "ABCDE"
                        },
                        "description": "Adjetivos"
            
            }

+ Response 201 (application/json)

        Result OK for new 

## Content [/contents/{content_id}]

Answer from a content through a *content_id*.

### Get a content [GET]
+ Request 

    + Headers

            Location: /contents/{content_id}

+ Response 200 (application/json)

    + Body

            {
                        "subject" :
                        {
                
                                    "description": "A..E",
                                    "options": "ABCDE"
                        },
                        "description": "Adjetivos"
            
            }

+ Response 204 

### Delete [DELETE]

+ Request 

    + Headers

            Location: /contents/{content_id}

+ Response 204

### Update [PUT]

+ Request 

    + Headers

            Location: /contents/{content_id}
    + Body

            {
                        "subject" :
                        {
                
                                    "description": "A..E",
                                    "options": "ABCDE"
                        },
                        "description": "Adjetivos"
            
            }
                
+ Response 201 (application/json)

        Result OK for new